
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_datamocktool'
version: '0.0.1'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'jaffle_shop'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

vars:
    dmt_mappings:
        test_suite_1:
            sources:
                raw:
                    customers: dmt__raw_customers_1
                    orders: dbt__raw_orders_1
            models:
                stg_payments: dmt__stg_payments_1
                stg_orders: dbt__stg_orders_1
        test_suite_2:
            sources:
                raw:
                    customers: dmt__raw_customers_2
                    orders: dbt__raw_orders_2
            models:
                stg_payments: dmt__stg_payments_2
                stg_orders: dbt__stg_orders_2